### ISSUE TITLE
Recruit a team

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/.net-buildpack#1]
If you're interested in running .NET apps on Cloud Foundry, then add a comment to this  issue.

Including details of the kind of apps you'd like to run is most helpful.

**Comment by mrdavidlaing** [comment]
@davidlaing 
- Standalone / worker apps that monitor & log events (eg, website uptime)
- ASP.NET WebAPI

**Comment by andypiper** [comment]
So there's a Heroku buildpack for Mono I think?

Additionally, the IronFoundry team just released support for v2 -> .NET apps on CF.

**Comment by andypiper** [comment]
Forked an existing Mono buildpack to https://github.com/andypiper/mono3-buildpack and noodling around with it. So far build breaks due to a path issue (/app/vendor absolute path, I've seen this with other buildpacks too). I tried modifying the path in the buildpack itself, but the issue still occurs.

... unfortunately, the buildpack downloads a 100Mb binary blob from S3 containing the Mono binaries. Doubly unfortunately, there are 63 script files in that tarball that all contain the same hardcoded absolute path to /app/vendor which will need to be modified. Nasty.

**Comment by lukebakken** [comment]
Count me in too, sounds interesting. Too bad Mono is so huge of a download right now.

**Comment by mrdavidlaing** [comment]
Welcome on board @lukebakken & @andypiper 

My intention is to start by integrating https://github.com/mrdavidlaing/stackato-buildpack-mono with https://github.com/IronFoundry/cloudfoundry-buildpack-clr - taking the vendored runtimes from the former and integrating with the structure of the latter.

Unfortunately mono is big (100MB compressed, 300MB uncompressed) - not sure there is much we can do about that, other than ensure its downloaded from us-east-1 S3.

**Comment by nebhale** [comment]
[Caching, caching, caching](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/util-caches.md).  I'd start by [bending the ear of the Cloud Foundry team](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/jre/openjdk.rb#L62) to get a read/write cache shared across all invocations of the buildpack.

**Comment by mrdavidlaing** [comment]
@lukebakken, @andypiper, @nebhale - welcome to the Team!

I'm going to lay a bit of groundwork (like getting https://github.com/cloudfoundry-community/builder-mono to produce usable mono .gz's), and then ping you for comments

**Comment by mrdavidlaing** [comment]
Anyone else - if you've arrived to the party late; Welcome! Come find us in one of the other issues

**Comment by nterry** [comment]
Is it too late to join? I was building my own buildpack when I stumbled upon this one. I have a lot of experience with tomcat and mod_mono, so we could add ASP.NET MVC apps to this pack as well.

**Comment by mrdavidlaing** [comment]
Welcome @nterry !

I'd love your help with creating an ASP.NET MVC container - https://github.com/cloudfoundry-community/.net-buildpack/issues/17
