### ISSUE TITLE
Bump Mono version to latest.

### ISSUE THREAD

**Issue by nterry** [cloudfoundry-community/.net-buildpack#19]
v3.2.0, while awesome, is missing a TON of bugfixes and JIT/GC optimizations. See http://www.mono-project.com/Release_Notes_Mono_3.2#New_in_Mono_3.2.3 for the latest release notes.

**Comment by mrdavidlaing** [comment]
Using cloudfoundry-community/builder-mono I've compiled mono 3.2.3.

See

https://ci-labs-buildpack-downloads.s3.amazonaws.com/mono/lucid/x86_64/index.yml

I have a test version of the buildpack at https://github.com/mrdavidlaing/.net-buildpack

@nterry - could you give it a whirl and let me know if you encounter any issues.

**Comment by mrdavidlaing** [comment]
@nterry Do you think the .net-buildpack should be running Mono using the new `--server` flag?

> New server focused flag. Run mono with --server to tell the runtime to target performance. With this release, this means an aggressive threadpool scheduler that creates additional threads faster.

Do you have any idea what the `--server` flag does to memory usage?  (given that memory is the "scarce resource" for a CF user.)

**Comment by nterry** [comment]
I believe that --server uses a lower memory footprint. Im not sure how, but it may force the new SGen GC to help. I definitely think that the --server flag should be set.

**Comment by mrdavidlaing** [comment]
@nterry - I don't have much evidence, but in my simple tests the --server flag seems to use 40% less memory, which is _brilliant_ for the CF use case.

Concerning Boehm vs SGen - I compile mono without the Boehm GC to help keep the download smaller.  See https://github.com/cloudfoundry-community/builder-mono/blob/master/remote-build-3.rb#L49 for the full build script I'm using.

(Updates & suggestions on how to build mono much appreciated; I can't claim to be much of an expert).

Anyway, #22 now includes the --server flag, and will be merged shortly.

**Comment by mrdavidlaing** [comment]
Hmm - after leaving my test app running for an hour, the memory usage has climbed back to close to previous levels.  Definitely not a degradation then; but perhaps not quite the miracle memory usage cure either :)

That being said, Mono seems very memory efficient, especially compared to something like Java!
