### ISSUE TITLE
Get mono v3.0.12 components into an S3 repository

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/.net-buildpack#2]
See work over at:

https://github.com/cloudfoundry-community/builder-mono

Which will culminate in http://ci-labs-buildpack-downloads.s3-website-us-east-1.amazonaws.com/mono/lucid/x86_64/index.yml

**Comment by mrdavidlaing** [comment]
Done.  Download sizes are as follows:

| repo tag | Mono Version | Tag | Profile(s) | Size(gz) |
| --- | --- | --- | --- | --- |
| [3.0.10-full](https://github.com/cloudfoundry-community/builder-mono/tree/3.0.10-full) | `3.0.10` | `mono-3.0.10` | net2,net35,net4,net45 | 100 MB |
| [3.0.12-full](https://github.com/cloudfoundry-community/builder-mono/tree/3.0.12-full) | `3.0.12` | `mono-3.0.12` | net2,net35,net4,net45 | 60 MB |
| [3.1.2-full](https://github.com/cloudfoundry-community/builder-mono/tree/3.1.2-full) | `3.1.2` | `mono-3.1.2` | net2,net35,net4,net45 | 60 MB |
| [3.1.2-net4](https://github.com/cloudfoundry-community/builder-mono/tree/3.1.2-net4) | `3.1.2` | `mono-3.1.2` | net2,net35,net4 | 33 MB |

**Comment by andypiper** [comment]
Wow that net45 stuff adds a lot of stuff eh! Nice sleuthing / experimentation though.

**Comment by mrdavidlaing** [comment]
Yep.  Also, it seems that by default mono ships with 2 garbage collectors; so in 3.0.12 + I switched one of them off.
