### ISSUE TITLE
Document high level buildpack design

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/.net-buildpack#3]
Like the cloudfoundry/java-buildpack, the .NET buildpack is composed of a number of components
- Runtimes (Mono, .NET etc) - equivalent to Java JREs
- Project Types (Console, Web etc) - equivalent to Java Containers 
- Frameworks (ASP.NET MVC, Web Forms etc) - equivalent to Java Frameworks

**Comment by mrdavidlaing** [comment]
First stab at: https://github.com/cloudfoundry-community/.net-buildpack/blob/master/docs/design.md

@lukebakken, @andypiper, @nebhale - could you give me some feedback on this initial component design.

Specifically, I'm not sure whether Project Types & Frameworks are in fact different things in the .NET world.

Perhaps they should be merged into a single component - Type (Console, ASP.NET MVC, ASP.NET Web Forms)?

**Comment by lukebakken** [comment]
@mrdavidlaing - thanks for getting the ball rolling on all of this.

I think there really are only two types of .NET apps that will be hosted in Cloud Foundry - Console and ASP.NET apps. I don't think differentiating by application framework is necessary since these apps should be totally self-contained when deployed ("bin deployable").

**Comment by mrdavidlaing** [comment]
@lukebakken,

Concerning types - I'm starting to think that containers is perhaps a better name; it will probably boil down to installing the dependancies and generating the "start" script to actually launch your application.
- Console -> no dependancies, with start script being "mono MyConsoleApp.exe" for Mono runtime and "MyConsoleApp.exe" for .NET CLR runtime
- IIS -> iishost.exe dependancy + startup script to launch iishost on the correct port
- xsp -> nginx + mono xsp + startup config to link nginx to xsp's fastcgi interface

Concerning frameworks - I've been poking into the [java-buildpack notion of frameworks](https://github.com/cloudfoundry/java-buildpack/tree/master/lib/java_buildpack/framework), and these seem to be mainly concerned with autoconfiguration - i.e, injecting DB connection params.

Maybe this is the right way to think of frameworks; ie, configuration frameworks, of which a specific app could have several:
- ADO.NET ConnectionStrings - http://msdn.microsoft.com/en-us/library/ms254494(v=vs.80).aspx 
- Log4NET Appenders - http://logging.apache.org/log4net/release/config-examples.html
- nLog Config - https://github.com/nlog/NLog/wiki/Configuration-file#wiki-configuration-file-format
