### ISSUE TITLE
How to debug flapping instance?

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/.net-buildpack#4]
A Mono v3.5 console app works fine with the smaller (33MB) Mono 3.2.0_net4 runtime.

```
$ cf push
Using manifest file manifest.yml

Uploading sample_commandline_app... OK
Stopping sample_commandline_app... OK

Preparing to start sample_commandline_app... OK
-----> Downloaded app package (8.0K)
-----> Downloaded app buildpack cache (33M)
Initialized empty Git repository in /tmp/buildpacks/.net-buildpack/.git/
-----> Downloading Mono 3.2.0_net4 from http://ci-labs-buildpack-downloads.s3.amazonaws.com/mono/lucid/x86_64/mono-3.2.0_net4.tar.gz (0.0s)
       Expanding Mono to vendor/mono (1.6s)
-----> Uploading droplet (33M)
Checking status of app 'sample_commandline_app'...........
  1 of 1 instances running (1 running)
Push successful! App 'sample_commandline_app' available at http://.
```

The same app with the larger (61MB) Mono 3.2.0_full runtime fails.

```
$ cf push
Using manifest file manifest.yml

Uploading sample_commandline_app... OK
Stopping sample_commandline_app... OK

Preparing to start sample_commandline_app... OK
-----> Downloaded app package (8.0K)
-----> Downloaded app buildpack cache (33M)
Initialized empty Git repository in /tmp/buildpacks/.net-buildpack/.git/
-----> Downloading Mono 3.2.0_full from http://ci-labs-buildpack-downloads.s3.amazonaws.com/mono/lucid/x86_64/mono-3.2.0_full.tar.gz (2.5s)
       Expanding Mono to vendor/mono (2.2s)
-----> Uploading droplet (61M)
Checking status of app 'sample_commandline_app'.....................
  0 of 1 instances running (1 flapping)
Push unsuccessful.
```

I can't figure out how to get log information out the the flapping instance to figure out what is going wrong:

`cf logs` fails:

```
$ cf logs
Using manifest file manifest.yml

Getting logs for sample_commandline_app #0... FAILED
CFoundry::NotFound: 404: 
cat ~/.cf/crash # for more details
```

`cf files` seems to be missing most of the "standard" files (eg: `startup` & `logs/`)

```
$ cf files sample_commandline_app
Getting file contents... OK

app/                                         -
tmp/                                         -
```

`cf crashlogs` is pretty unhelpful.

```
$ cf crashlogs sample_commandline_app
Getting logs for sample_commandline_app #a3e8acdd95858819edb6dae97a68217e... FAILED
CFoundry::NotFound: 404: 
cat ~/.cf/crash # for more details
```

**Comment by mrdavidlaing** [comment]
Here is a diff of a verbose call to cf logs for both working (left) and flapping (right)

http://www.diffchecker.com/bo8iib9x

**Comment by lukebakken** [comment]
Hey @mrdavidlaing  - are you pushing to the "official" CF environment? The first thing that came to mind was that the 61M push timed out and CF never actually tried to start the app.

If I spin up my local V2 env I should be able to use this buildpack, correct? Would you mind adding your command line app to this repo or send it to me so I can use the same code? Thanks!

**Comment by mrdavidlaing** [comment]
@lukebakken,
1. I'm getting the errors only when targeting run.pivotal.io.  I agree - its like CF never started, or only "half started".
2. The 3.2.0_full runtime works on a local [cf-vagrant-installer](https://github.com/Altoros/cf-vagrant-installer)
3. Yes, you should be able to use this buildpack on your local V2 env.  Have just added the compiled version of my sample app. `cd /path/to/this/repo/spec/fixtures/sample_commandline_app && cf push` should do it

```
[01:25][mrdavidlaing@maccy001:~/Projects/CloudFoundry/.net-buildpack/spec/fixtures/sample_commandline_app(master)]$ cf push
Using manifest file manifest.yml

Uploading sample_commandline_app... OK
Stopping sample_commandline_app... OK

Preparing to start sample_commandline_app... OK
Checking status of app 'sample_commandline_app'...
  0 of 1 instances running (1 starting)
  0 of 1 instances running (1 starting)
  1 of 1 instances running (1 running)
```

**Comment by mrdavidlaing** [comment]
@andypiper, @nebhale; Can you (or one of your contacts) help @lukebakken and myself with how to debug a flapping instance.

Why this specific instance is flapping is less relevant that figuring out how to get our hands on some debug information.

The process that works on a local cf-vagrant-installer fails when run against run.pivotal.io.

Specifically, staging seems to succeed; but app startup fails; and we can't figure out how to get access to some debugging information that gives a clue as to why.

**Comment by andypiper** [comment]
Best thing to do would be to open a ticket on support.cloudfoundry.com initially, and perhaps also drop a link to this thread on vcap-dev.

**Comment by mrdavidlaing** [comment]
support.cloudfoundry.com ticket at http://cloudfoundry.zendesk.com/entries/25116287-How-to-get-details-what-failed-in-an-app-deploy-when-cf-logs-fails

**Comment by andypiper** [comment]
Looks like @danhigham may be taking a look (judging from his fork of the repo)

**Comment by mrdavidlaing** [comment]
Thanks for [@danhigham's genius debugging](http://cloudfoundry.zendesk.com/entries/25116287-How-to-get-details-what-failed-in-an-app-deploy-when-cf-logs-fails?page=1#post_23890472), the issue seems to be related to the amount of RAM available to tar/gzip when extracting the staged droplet.tar.gz in your app's warden container

More that 256MB available -> works.

```
$ cf scale --memory 256
Using manifest file manifest.yml

Scaling sample_commandline_app... OK
Stopping sample_commandline_app... OK

Preparing to start sample_commandline_app... OK
Checking status of app 'sample_commandline_app'...
0 of 1 instances running (1 starting)
0 of 1 instances running (1 starting)
0 of 1 instances running (1 starting)
1 of 1 instances running (1 running)
```

Less, and it fails

```
$ cf scale --memory 128
Using manifest file manifest.yml

Scaling sample_commandline_app... OK
Stopping sample_commandline_app... OK

Preparing to start sample_commandline_app... OK
Checking status of app 'sample_commandline_app'...
0 of 1 instances running (1 starting)
0 of 1 instances running (1 starting)
0 of 1 instances running (1 down)
0 of 1 instances running (1 starting)
0 of 1 instances running (1 flapping)
Push unsuccessful.
```

**Comment by mrdavidlaing** [comment]
Looks like the [droplet extraction code](https://github.com/cloudfoundry/dea_ng/blob/master/lib/dea/instance.rb#L426-L434) could be the source of the error

```
  def promise_extract_droplet
      Promise.new do |p|
        script = "cd /home/vcap/ && tar zxf #{droplet.droplet_path}"

        promise_warden_run(:app, script).resolve

        p.deliver
      end
    end
```

Note that extraction of the droplet happens in the context of your apps warden container (ie, is subject to your app's memory limits)

**Comment by mrdavidlaing** [comment]
Hmm; some simple experiments suggest that `tar zxf` is pretty memory efficient (at least on OSX) - so I'm not convinced this is the source of the problem

```
$ /usr/bin/time -l tar zxf mono-3.2.0_full.tar.gz 
        6.50 real         0.98 user         0.54 sys
   1044480  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
       261  page reclaims
        18  page faults
         0  swaps
       115  block input operations
       423  block output operations
         0  messages sent
         0  messages received
         0  signals received
       127  voluntary context switches
       451  involuntary context switches
```

Out of interest, `gzip -d file.tar.gz && tar xf file.tar.gz` is more memory efficient

```
/usr/bin/time -l gzip -d mono-3.2.0_full.tar.gz && tar xf mono-3.2.0_full.tar 
        3.14 real         1.71 user         0.19 sys
    659456  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
       182  page reclaims
         0  page faults
         0  swaps
         7  block input operations
        20  block output operations
         0  messages sent
         0  messages received
         0  signals received
       123  voluntary context switches
        23  involuntary context switches
```

**Comment by lukebakken** [comment]
@mrdavidlaing - there is a chance that the memory limits imposed by warden are different than the memory usage reported by `time` - i.e. maybe the limit is on total virtual memory size versus resident size (if that's what `time` reports). I'll see if I can reproduce using `wsh` and warden on my local V2 VM.

**Comment by mrdavidlaing** [comment]
@lukebakken - Thanks!  That will be really helpful.

Turns out you can use `cf events <app>` to get some detail of a flapping app:

```
$ cf events sample_commandline_app
Using manifest file manifest.yml

Getting events for sample_commandline_app... OK

time                        instance index   description                     exit status 
2013-08-06 13:46:43 +0000   0                Script exited with status 137   Failure (-1)
2013-08-06 13:46:43 +0000   0                can't convert nil into String   Failure (-1)
```

Not really sure what that means; but at least it is something!

**Comment by mrdavidlaing** [comment]
Hmm - [StackOverflow users](http://stackoverflow.com/questions/1041182/why-does-my-perl-script-exit-with-137) say 137 means SIGKILL, and is often related to Out Of Memory errors...

**Comment by mrdavidlaing** [comment]
I'm closing this issue, since we have a "solution".
1.  Use `cf events` to get details of what went wrong during app deployment
2.  In this specific case, something (we suspect `tar`) is consuming too much memory at application deploy.  A hacky fix is to allocate more memory to the instance
